# Generated by Django 4.0.2 on 2022-02-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='datahora',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='comanda',
            name='valor_quarto',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
