# Generated by Django 4.0.2 on 2022-03-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_painel_quarto'),
    ]

    operations = [
        migrations.AddField(
            model_name='painel',
            name='pessoas',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
