# Generated by Django 4.0.2 on 2022-03-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocupacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocupacao',
            name='tipo',
        ),
    ]
