# Generated by Django 4.0.2 on 2022-03-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
