# Generated by Django 4.0.2 on 2022-02-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
