# Generated by Django 4.0.2 on 2022-03-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='fundo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
