# Generated by Django 4.0.2 on 2022-02-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emeil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emeil',
            name='autenticacao',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
