# Generated by Django 4.0.2 on 2022-04-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cabeca',
            new_name='Infos',
        ),
    ]
